feat: CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -20,12 +20,34 @@ jobs:
       uses: actions/setup-go@v4
       with:
         go-version: ${{ matrix.go }}
-    # TODO: enable testing in CI, currently blocked by ICMP requests in actions virtual environment
-    # - run: "go test ./..."
-    - run: "go mod tidy"
-    - run: "go vet ./..."
-    - uses: dominikh/staticcheck-action@v1.3.0
+    # TODO: enable connectivity testing in CI, currently blocked by ICMP requests in actions virtual environment
+    - name: tidy
+      run: go mod tidy
+
+    - name: test
+      env:
+        CI: enabled
+      run: |
+        go test -v -coverprofile="coverage.out" ./...
+
+    - name: lint
+      uses: dominikh/staticcheck-action@v1.3.0
       with:
         version: "2023.1.3"
         install-go: false
         # cache-key: ${{ matrix.go }}
+
+    - name: cov
+      if: matrix.os == 'ubuntu-latest'
+      env:
+        COVERAGE_GATE: 72
+      run: |
+        totalCoverage=`go tool cover -func="coverage.out" | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+        echo "Current test coverage : $totalCoverage %"
+        if (( $(echo "$totalCoverage $COVERAGE_GATE" | awk '{print ($1 >= $2)}') )); then
+          echo "OK"
+        else
+          echo "Test coverage is below threshold of $COVERAGE_GATE%."
+          echo "Failed"
+          exit 1
+        fi
